### PR TITLE
tiny typos

### PR DESCRIPTION
**Pull request by soulseekah**
Mentioned in issue #1

### CODE REVIEW

**Comment by Swizec** [comment]
Thanks!

I'll merge this as soon as I figure out how to merge into the writing branch.

**Comment by dideler** [comment]
@Swizec, the easiest way would be for @soulseekah to change the destination branch (he might have to close and reopen the pull request). You can also try a [patch and apply](https://help.github.com/articles/using-pull-requests#merging-a-pull-request).

**Comment by soulseekah** [comment]
The patch-1 branch is diverged by another two commit as https://github.com/Swizec/nightowls/issues/5 shows.
So what you'll have to do (if you're feeling adventerous) is:

``` bash
git checkout origin/writing
git remote add soulseekah https://github.com/soulseekah/nightowls.git
git fetch soulseekah
git cherry-pick soulseekah/patch-1 --ff 6e3415f
git cherry-pick soulseekah/patch-1 --ff 93c2d63
git push origin/writing
git remote rm soulseekah
```

Alternatively simply fix them by hand and close this request.

**Comment by soulseekah** [comment]
I figured it would be easier to do what @dideler suggested than to have you pick out and fetch. So here it goes, take 3:  https://github.com/Swizec/nightowls/pull/6

My apologies for all the pull request havoc, I wasn't aware of the writing branch.

**Pull request closed without merging**
